In [3]:
import numpy as np

In [31]:
a = [[11, 12 , 13],[21, 22, 23],[31, 32, 33]]

In [57]:
A = np.array (a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [8]:
A.ndim

2

In [9]:
A.shape

(3, 3)

In [10]:
A.size

9

In [11]:
A=np.array([[1,0,1],[0,1,1]])
A.shape

(2, 3)

In [14]:
A:[[A[0][0], A[0][1], A[0][2]], [A[1][0], A[1][1], A[1][2]], [A[2][0], A[2][1], A[2][2]]]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [22]:
A:[[A[0][0], A[0][1], A[0][2]], [A[1][0], A[1][1], A[1][2]]]

In [23]:
A

array([[1, 0, 1],
       [0, 1, 1]])

In [56]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [27]:
A[1][2]

23

In [28]:
A[0][0]

11

In [30]:
A=np.array([[1,0,1],[2,2,2]])
A[0][1]

0

In [78]:
A[1:2,1]

array([22])

In [89]:
x = np.array ([[1, 0],[0, 1]])
y = np.array ([[2, 1],[1, 2]])
Z = x + y
Z

array([[3, 1],
       [1, 3]])

In [88]:
y = np.array ([[2, 1],[1, 2]])
z = 2*y
z

array([[4, 2],
       [2, 4]])

In [91]:
x = np.array ([[1, 0],[0, 1]])
y = np.array ([[2, 1],[1, 2]])
z = x*y
z

array([[2, 0],
       [0, 2]])

In [94]:
A = np.array([[0, 1, 1],[1, 0, 1]])
B = np.array([[1, 1],[1, 1],[-1, 1]])
C = np.dot(A, B)
C

array([[0, 2],
       [0, 2]])

In [95]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [97]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [98]:
with open("Exampl1.txt","r") as File1:

    file_stuff=File1.readline ()

    print(file_stuff)

FileNotFoundError: [Errno 2] No such file or directory: 'Exampl1.txt'

In [100]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [101]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])